export const GET_MOVIE_DATA_REQ = "GET_MOVIE_DATA_REQ";
export const GET_MOVIE_DATA_SUCCESS = "GET_MOVIE_DATA_SUCCESS";
export const GET_MOVIE_DATA_FAILURE = "GET_MOVIE_DATA_FAILURE";

export const FILTER_BY_GENRE = "FILTER_BY_GENRE";